dist: bionic
# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 7.2
  - 7.1

# Commands you want to run that will verify your build.
script:
   - '! find . -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
