Use Bookings;
CREATE TABLE Rooms (
entryID INT NOT NULL AUTO_INCREMENT,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
StudentID VARCHAR(20), Society VARCHAR(20), Room VARCHAR(50), 
booking_for TIMESTAMP NULL DEFAULT NULL,
booking_end TIMESTAMP NULL DEFAULT NULL,
Activity VARCHAR(100),
 PRIMARY KEY(entryID));
